### ISSUE TITLE
RBF sites/links handling

### ISSUE THREAD

**Issue by TamerRizk** [cbergmeir/RSNNS#1]
krui_getSiteName chokes when using sites within the network and at least RadialBasisLearning due to incomplete link handling. Solution for learn_f.cpp:3724 as follows:

```
if (NetInitialize || LearnFuncHasChanged) {
  FOR_ALL_UNITS(unit_ptr) {
    if UNIT_HAS_SITES( unit_ptr ){
      FOR_ALL_SITES_AND_LINKS(unit_ptr, site_ptr, link_ptr) {
        link_ptr->value_a = 0.0;
      }
    }else{
      FOR_ALL_LINKS(unit_ptr, link_ptr) {
        link_ptr->value_a = 0.0;
      }
    }
  }
}
```

Also, the following pointer operations in kr_mem.cpp look kind of suspicious. Should post increments be used instead? 

```
tmp_ptr = ++link_array;
tmp_ptr = ++site_array;
```

**Comment by cbergmeir** [comment]
Hi, thanks for providing the fix, I just committed it here on github so that it will be included in the next version. The issue you raise about kr_mem.cpp: I'm not so sure because I didn't develop the code. But it is certainly true that there are some memory leaks in the code, which should be fixed for the next version.
